Sitegeist:
  CsvPO:

    # render visible hint for missing translations
    # is enabled by default for debug mode
    debugMode: false

    # Control which translation options are available in
    # the backend module and the cli
    management:
      # enable locallization overrides, disables in contexts
      # without database like visual regression testing
      enabled: true

      # package keys to scan for translation files
      packageKeys: []

      # list of locales to manage in the backend module
      locales: ['en']

      # file extension to search for translations
      fileExtension: '.translation.csv'

      # folder inside the package resources to search for translations
      resourcePath: 'Private/Fusion'

Neos:
  Fusion:
    defaultContext:
      CsvPO: 'Sitegeist\CsvPO\Eel\TranslationHelper'

  Neos:
    modules:
      administration:
        submodules:
          translation:
            label: 'Translations'
            description: 'Show and alter component translations'
            icon: 'icon-language'
            controller: 'Sitegeist\CsvPO\Controller\TranslationController'
            privilegeTarget: 'Sitegeist.CsvPO:ManageTranslationLabels'


